### ISSUE TITLE
Restricted color of icons in Vitamin

### ISSUE THREAD

**Issue by MelanieTainon** [Decathlon/vitamin-design#218]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [ ] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [X] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [X] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Current behavior 😯

Hello,
I've done a Figma with grey icon. When I give it to the developper, he says me that in Vitamin, he is constrained by 8 colors when he want to choose the color of the icons (cf screenshot). There is no grey. Is this normal? I didn't see this constraint on Vitamin rules.

### Expected behavior 🤔

Have more colors?

### Context 🔦

When developper try to change the color of the icons

### Screenshots / Videos 📸

<img width="1700" alt="Capture d’écran 2023-03-10 à 16 19 47" src="https://user-images.githubusercontent.com/126483383/224674922-f5d38450-00e7-4033-984c-4378debf14ed.png">
![Capture d’écran 2023-03-10 à 16 20 40](https://user-images.githubusercontent.com/126483383/224674944-4be6cf02-03e1-4e99-bc2b-a7198699cdab.png)

```[tasklist]
### Tasks
- [ ] https://github.com/Decathlon/vitamin-web/issues/1389
```

**Comment by lauthieb** [comment]
Hi @MelanieTainon, thanks for your request.
You're right, we only accept these colors.
I just ping @Decathlon/design-system-core-team-design privately, we will keep you informed asap :)

**Comment by lauthieb** [comment]
Hi again @MelanieTainon, thanks a lot for your issue because we missed a lot of colors, you're right :)
I'll take this in this issue on vitamin-web: https://github.com/Decathlon/vitamin-web/issues/1389
I keep you informed when this will be merged and released.

**Comment by lauthieb** [comment]
@MelanieTainon that's merged and in production 🎉
