### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by Sabrinavigil** [Decathlon/vitamin-design#7]
### Duplicates ❌

- [X] I have searched the existing issues

### Which Figma library is concerned?

Not related to one Figma library

### Summary 💡

Improve button with properties and tokens. 
Add a "is loading" variation.
Rework paddings on “with icon” variant (make it pixel, perfect). 
Add missing reversed variation. 

### Examples 🌈

https://www.figma.com/community/file/1117085093344345579
https://www.figma.com/community/file/1115858697474114875
https://www.figma.com/community/file/1111717810979847533

### New 🆕

- [ ] Validated in a grooming session

### Backlog 📋

- [ ] Has a good summary
- [ ] Has example link(s)

### Design in progress 🏗

- [ ] Analysis _(functional & technical)_
- [ ] Design refinement
- [ ] Dev qualification _(properties, breakpoints, tokens etc.)_
- [ ] Documentation refinement _(inside the Figma branch)_

### Design review 👀

- [ ] Figma branch merged
- [ ] Documentation review _(and move the documentation into Vitamin Documentation Figma file)

### Ready to dev 👍

- [ ] Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_

### Dev in progress 💻

- [ ] All issues are resolved _(to replace with issues links)_

**Comment by MARIEDELATTRE** [comment]
**DONE:**

- Component properties added.
- Emoji in layers names.

**TODO:**

- Doc in files (with plugin prop stars cf Vitamin - Improvements V0 & V1).
- Add icon button component (not a variant, it's component itself).

**Comment by Sabrinavigil** [comment]
> **DONE:**
> 
> - Component properties added.
> - Emoji in layers names.
> 
> **TODO:**
> 
> - Doc in files (with plugin prop stars cf Vitamin - Improvements V0 & V1).
> - Add icon button component (not a variant, it's component itself).
> - Add a "is loading" variation.
> - Rework paddings on “with icon” variant (make it pixel, perfect).
> - Add missing reversed variation.

**Comment by Sabrinavigil** [comment]
Add a circular variation :
![Image](https://user-images.githubusercontent.com/65814825/185344689-ddc54d61-b9ee-4b14-a4d0-2a06bcf8df47.png)

**Comment by Sabrinavigil** [comment]
Add a critical button : 
![Image](https://user-images.githubusercontent.com/65814825/186941303-520ff22c-1303-4d31-948d-99c509a4ceb5.png)
Thanks @Tlahey :)

**Comment by Sabrinavigil** [comment]
An other use case of the circular button from @LoicVeira
![image](https://user-images.githubusercontent.com/65814825/199996671-2a12380a-5a81-4abe-a354-594d74800d0e.png)

**Comment by lauthieb** [comment]
This topic has been launched in beta test.
However, its status in the board no longer reflects the current reality, so it has been moved to our "New" column.
We will keep you informed of the different advances.
Thank you.

**Comment by lauthieb** [comment]
Hello,
As @Z08MURBE proposed, we will also need to take care about adding a loading state for the button that could be useful.
Cf. this issue: https://github.com/Decathlon/vitamin-design/issues/186
Thank you again @Z08MURBE for your proposition.
Laurent
